env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - eslint:recommended
  - "@vue/typescript/recommended"
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - prettier/vue
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
  - prettier
rules:
  prettier/prettier: "error"
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
