name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Connect to EC2 instance and clone project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            if [ ! -d codeex-quiz ]; then
              mkdir codeex-quiz
            fi

            cd codeex-quiz
            if [ ! -d codeex-quiz-client ]; then
              git clone https://github.com/cs-fedy/codeex-quiz-client.git
            fi

            cd codeex-quiz-client
            git fetch origin main
      - name: Run the app
        run: |
          cd codeex-quiz/codeex-quiz-client
          yarn && yarn run dev
